bot:
  token: "DISCORD_BOT_TOKEN"
  teamroleid: "TEAM_ROLE_ID"
  guildid: "GUILD_ID"
  registerchannelid: "REGISTER_CHANNEL_ID"
  logchannelid: "LOG_CHANNEL_ID"
database:
  host: "localhost"
  port: 5432
  database: "meineDatenbank"
  username: "dbUser"
  password: "dbPasswort"
