bot:
  token: "DISCORD_BOT_TOKEN"
  teamroleid: "TEAM_ROLE_ID"
  guildid: "GUILD_ID"
  registerchannelid: "REGISTER_CHANNEL_ID"
  logchannelid: "LOG_CHANNEL_ID"
database:
  host: "localhost"
  port: 5432
  database: "meineDatenbank"
  username: "dbUser"
  password: "dbPasswort"
settings:
  chatprefix: "&8[&6AGC MineTools&8] &7• "
  noPermissions: "&cDu darfst diesen Befehl nicht ausführen."
messages:
  registerembedmessage: "Minecraft Version: VERSIONHIER \n\nServeraddress: link.de \n\nUm dich zu registrieren, drücke auf den Button \"Registrieren\""
lookup:
  commandUsage: "&6/lookup <Player>"
  notLinked: "&6Unter diesem Namen konnte kein verknüpfter Account gefunden werden."
  playerOnlyCommand: "&cDieser Befehl kann nur von einem Spieler ausgeführt werden."
  inventoryTitle: "&8Account Lookup"
  discordTitle: "&9Discord"
  discordIdTitle: "&bDiscord ID"
  discordIdDesc: "&7Klicken um ID aus dem Chat zu kopieren"
  lastLoginTitle: "&6Letzter Login"
  registeredTitle: "&eRegistriert seit"
  copyIdChatMessage: "&6Klicke hier um die ID des Nutzers zu kopieren."
  copyIdChatHover: "&8Kopiert folgende ID in deine Zwischenablage: &7"
  ipAddressTitle: "&5IP-Adresse"
ban:
  banTitle: "&8[&6AGC MineTools&8] &7"
  commandUsage: "&6/ban <Player> <Begründung>"
  noPlayerFound: "&6Dieser Spieler wurde nicht gefunden."
  playerMessage: "&6Der Spieler wurde erfolgreich vom Server gebannt."
  banMessage: "&cDu wurdest permanent vom Server gebannt!"
  banReason: "&8Begründung: "
  noticeMessage: "&8Wenn du der Meinung bist, du wurdest zu unrecht gebannt, dann wende dich bitte an den Anime & Gaming Café-Support."
  socialLink: "&bhttps://discord.gg/animegamingcafe/"
unban:
  commandUsage: "&6/unban <Player>"
  playerNotBanned: "&6Dieser Spieler ist nicht gebannt."
  playerMessage: "&6Der Spieler wurde erfolgreich entbannt!"
kick:
  kickTitle: "&8[&6AGC MineTools&8] &7"
  commandUsage: "&6/kick <Player> <Begründung>"
  noPlayerFound: "&6Dieser Spieler wurde nicht gefunden."
  playerMessage: "&cDer Spieler wurde erfolgreich vom Server geworfen."
  kickMessage: "&cDu wurdest vom Server geworfen."
  kickReason: "&8Begründung: "
  noticeReason: "&8Bitte halte dich immer an unsere Server-Regeln."
op:
  consoleOnly: "&cDieser Befehl kann aus Sicherheitsgründen nur in der Server-Console ausgeführt werden"
  commandUsage: "&6/op <Player>"
  noPlayerFound: "&cDer angegebene Nutzer wurde nicht gefunden."
  playerMessage: "&6Der angegebene Spieler ist nun ein Serveroperator!"
deop:
  consoleOnly: "&cDieser Befehl kann aus Sicherheitsgründen nur in der Server-Console ausgeführt werden"
  commandUsage: "&6/deop <Player>"
  noPlayerFound: "&cDer angegebene Nutzer wurde nicht gefunden."
  playerMessage: "&6Der angegebene Spieler ist nun kein Serveroperator mehr!"
kill:
  commandUsage: "&6/kill <Player>"
  playerNotFound: "&6Der angegebene Spieler wurde nicht gefunden."
  playerMessage: "&6Der Spieler wurde erfolgreich umgebracht."
reload:
  commandUsage: "&6/reload"
  reloadMessage: "&6Die Config des Plugins wurde erfolgreich neugeladen."
heal:
  commandUsage: "&6/heal [Player]"
  playerNotFound: "&6Der angegebene Spieler wurde nicht gefunden."
  playerMessageSelf: "&6Deine Herzen wurde erfolgreich aufgefüllt."
  playerMessage: "&6Die Herzen des Spielers wurden erfolgreich aufgefüllt."
gamemode:
  commandUsage: "&6/gamemode <GameMode> [Spieler]"
  playerNotFound: "&6Der angegebene Spieler wurde nicht gefunden."
  playerMessageSelf: "&6Dein Spielmodus wurde erfolgreich geändert auf: &8"
  playerMessage: "&6Der Spielmodus wurde erfolgreich geändert auf: &8"
  invalidGameMode: "&6Der angegebene Spielmodus existiert nicht."
uwu:
  playerMessage: "&6Das Herz wurde erfolgreich erzeugt."
  playerOnly: "&6Dieser Befehl kann nur von einem Spieler ausgeführt werden."